### ISSUE TITLE
非常期待

### ISSUE THREAD

**Issue by 551685830** [formilyjs/antdv-x3#2]
HI，非常高兴看到Formily社区全面拥抱VUE3有了新动向，想替广大Formily迷问下。
- 接下来是否有大的时间计划表
- 整个RoadMap是如何规划的
- designable是否会考虑进行VUE3的移植

**Comment by transtone** [comment]
https://github.com/cca313/antdv-x3

**Comment by zhouxinyong** [comment]
antdv的vue3版本还在开发中，预计节后会整合进行测试和发版

**Comment by transtone** [comment]
> antdv的vue3版本还在开发中，预计节后会整合进行测试和发版

马上315了，要不要对空代码项目进行打假 🔢

**Comment by LanJamRom** [comment]
近期会有动静吗？ @zhouxinyong

**Comment by hesperup** [comment]
@zhouxinyong   还有计划吗

**Comment by transtone** [comment]
https://github.com/formilyjs/antdv-x3/projects/1
终于更新了一把，加油！

**Comment by VincentDream** [comment]
又完全没有动静了，还是非常期待的

**Comment by zhouxinyong** [comment]
抱歉，最近公司卷业务，进展比较慢，会在忙完后补上进度！！！

**Comment by transtone** [comment]
终于有内容了，不容易呀，给作者点赞👍

**Comment by zhouxinyong** [comment]
整体vue3的代码已经完成了，欢迎大家提PR和ISSUE

**Comment by VincentDream** [comment]
给作者点赞👍，貌似文档打不开https://antdv-x3.formilyjs.org

**Comment by transtone** [comment]
@zhouxinyong  https://github.com/LanJamRom/formily-antdv-x3 这个项目和本项目有什么关系? 这个项目都发 npm 了，本项目还没发 :(

**Comment by LanJamRom** [comment]
> @zhouxinyong https://github.com/LanJamRom/formily-antdv-x3 这个项目和本项目有什么关系? 这个项目都发 npm 了，本项目还没发 :(

这个只是我等不急了，迁移了一点组件过来用用，还是等 @zhouxinyong 发版吧

**Comment by wsxe9988** [comment]
designable是否会考虑进行VUE3+andv-x3的移植呢，作者大大

**Comment by wanjidong** [comment]
@

> 整体vue3的代码已经完成了，欢迎大家提PR和ISSUE

不知道大佬什么时候能发版。

**Comment by zhouxinyong** [comment]
> designable是否会考虑进行VUE3+andv-x3的移植呢，作者大大

有这个想法

**Comment by zhouxinyong** [comment]
已经开始发版了，这个issue先close掉了
